
vulnerabilities:
- id: CVE-2024-27304
  statement: lnd related, Not using the function. Ignored.
- id: GHSA-7jwh-3vrq-q3m8
  statement: lnd related, Not using the function. Ignored.
- id: CVE-2024-27289
  statement: lnd related, Not using the function. Ignored.
- id: CVE-2024-38359
  statement: lnd related, Not using the function. Ignored.
