name: docker_publish

on:
  push:
    branches:
    - 'main'
    tags:
    - '*'

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@v0.7.0
    with:
     run-unit-tests: true
     run-integration-tests: true
     run-lint: true

  docker_pipeline:
    needs: ["lint_test"]
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@huy/add-docker-sec
    secrets: inherit
    with:
     publish: true
